#include<iostream>
using namespace std;

/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int main()
{
  long long n=4e6;
  long long sum=0;
  int first=1,second=2;
  cout<<n<<endl;
  while(second <= n){
  	if(second%2==0) sum += second;
  	
  	second = first + second;
  	first = second - first;
  }
  cout<<sum<<endl;// 4613732
return 0;
}

